version: '3'
services:
  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - kafka

  inventory-service:
    build: ./inventory-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - kafka

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
